### ISSUE TITLE
Question : not using the contact email in the confirm url

### ISSUE THREAD

**Issue by CecileBr** [WordPressUtilities/wpunewsletter#1]
Hi @Darklg,

I wondered if it would be possible to not use the contact email in the confirm url. I tested it on my side, it works but I wanted to know if there is a specific reason to use the secret key AND the email.

Thanks!

**Comment by Darklg** [comment]
@CecileBr hi ! simply to avoid any -unlikely- duplicate. The secretkey is indeed an md5 hash of a timestamp and the email, but md5 collisions exists, so adding the email removes this -still unlikely- risk.
